services:
  orders-service:
    image: orders-service
    build:
      context: .
      dockerfile: src/OrdersService/OrdersService.Api/Dockerfile
    ports:
      - "5172:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080

  sellers-service:
    image: sellers-service
    build:
      context: .
      dockerfile: src/SellersService/SellersService.Api/Dockerfile
    ports:
      - "5009:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080

  payment-service:
    image: payment-service
    build:
      context: .
      dockerfile: src/PaymentService/PaymentService.Api/Dockerfile
    ports:
      - "5289:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080