services:
  # Own services
  orders-service:
    image: orders-service
    build:
      context: ./src/OrdersService
      dockerfile: OrdersService.Api/Dockerfile
    ports:
      - "5172:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - orders-mongodb

  sellers-service:
    image: sellers-service
    build:
      context: ./src/SellersService
      dockerfile: SellersService.Api/Dockerfile
    ports:
      - "5009:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - sellers-mongodb

  payment-service:
    image: payment-service
    build:
      context: ./src/PaymentService
      dockerfile: PaymentService.Api/Dockerfile
    ports:
      - "5289:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - payment-mongodb

  # MongoDB instances for each service
  orders-mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - orders_mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=orders-database

  sellers-mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - sellers_mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=sellers-database

  payment-mongodb:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - payment_mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=payment-database

  zookeeper:
    image: bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.4
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://kafka:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - 8090:8080
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092,
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - kafka
      - zookeeper
      - orders-service
      - sellers-service
      - payment-service

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  orders_mongodb_data:
    driver: local
  sellers_mongodb_data:
    driver: local
  payment_mongodb_data:
    driver: local