services:
  orders-service:
    image: orders-service
    build:
      context: ./src/OrdersService
      dockerfile: OrdersService.Api/Dockerfile
    ports:
      - "5172:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080

  sellers-service:
    image: sellers-service
    build:
      context: ./src/SellersService
      dockerfile: SellersService.Api/Dockerfile
    ports:
      - "5009:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080

  payment-service:
    image: payment-service
    build:
      context: ./src/PaymentService
      dockerfile: PaymentService.Api/Dockerfile
    ports:
      - "5289:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080